/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage1;
//32Bit

import java.awt.FlowLayout;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JPanel;
import static newpackage1.NewJFrame.jMenu5;
import static newpackage1.NewJFrame.jMenuItem4;
import static newpackage1.NewJFrame.jMenuItem6;
import static newpackage1.NewJFrame.jMenuItem7;
import static newpackage1.NewJFrame.jMenuItem9;
// jMenuItem9
/**
 *
 * @author Zlati
 */
public class LoginForm extends javax.swing.JFrame {

    public NewJFrame frame;
    ResultSet rs = null;

//  String grp = (String) jComboBox3.getSelectedItem();
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        FlowLayout layoutPanel = new FlowLayout();
        JPanel panel = new JPanel(layoutPanel);
        JButton button = new JButton("jButton");
        panel.add(button);
        panel.setVisible(true);

        initComponents();

    }

    
    public static String getUserA() {
        String User = jTextField_Username.getText();

        return User;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_Username = new javax.swing.JLabel();
        jLabel_Password = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jButton_Login = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setIconImages(null);
        setResizable(false);

        jLabel_Username.setText("Username:");

        jLabel_Password.setText("Password:");

        jPasswordField_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_PasswordKeyPressed(evt);
            }
        });

        jButton_Login.setText("Login");
        jButton_Login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton_LoginFocusGained(evt);
            }
        });
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });

        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRATOR", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "Whipcream", "USER", "F2 WH" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(75, 119, 190));
        jPanel1.setAutoscrolls(true);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextField1.setText("NJORO CANNING FACTORY COST ANALYSIS");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage1/secrecy-icon.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jTextField2.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Username)
                                    .addComponent(jLabel_Password))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Username)
                                    .addComponent(jPasswordField_Password)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_Username)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel_Password))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Login)
                            .addComponent(jButton_Cancel)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        setBounds(500, 250, 521, 226);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
    LoginForme();

    }//GEN-LAST:event_jButton_LoginActionPerformed

    public void LoginForme() {
         String grp = (String) jComboBox1.getSelectedItem();
        String unamee = jTextField_Username.getText();
        String pwad = String.valueOf(jPasswordField_Password.getPassword());
//        jComboBox1.removeAllItems();
        try {
            PreparedStatement claese = db_Connection.getInstance().prepareStatement("select * from logintbl where username=? and password=? and status=?");
            claese.setString(1, unamee);
            claese.setString(2, pwad);
             claese.setString(3, grp);
            rs = claese.executeQuery();
            while (rs.next()) {
                String pudii = rs.getString("status");
                if (pudii.equals("ADMINISTRATOR")) {

                    NewJFrame mf = new NewJFrame();

                    mf.setVisible(true);
                    
                    jTextField2.setText(rs.getString("class"));
                     jComboBox1.setSelectedItem(rs.getString("class"));
                   

                    jComboBox1.setEnabled(false);
                    jMenu5.setVisible(true);
                    ExportAndImport exp = new ExportAndImport();
                    exp.setVisible(false);
                    LoginForm exep = new LoginForm();
                    exep.setVisible(false);
//                    jPasswordField_Password.setText(null);
                    this.hide();
                } else if (pudii.equals("USER")) {
                    try {
                        NewJFrame mf = new NewJFrame();
                        mf.setVisible(true);

//                        jComboBox1.addItem(rs.getString("class"));
//                        jComboBox1.setSelectedItem(rs.getString("class"));
//                        jComboBox1.setEnabled(false);
                        jTextField2.setText(rs.getString("class"));
//                 jTextField3.setText(rs.getString("class"));
jComboBox1.setSelectedItem(rs.getString("class"));
                        jMenu5.setVisible(false);
                        jMenuItem9.setVisible(false);
                        jMenuItem4.setVisible(false);
                        jMenuItem7.setVisible(false);
                        jMenuItem6.setVisible(false);
                        ExportAndImport exp = new ExportAndImport();
                        exp.setVisible(false);
                        LoginForm exep = new LoginForm();
                        exep.setVisible(false);
//                        jPasswordField_Password.setText(null);
                        this.hide();

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
   
   
//        if(jComboBox1.getSelectedItem()=="F1"||jComboBox1.getSelectedItem()=="F2"||jComboBox1.getSelectedItem()=="F3"||jComboBox1.getSelectedItem()=="F4"||jComboBox1.getSelectedItem()=="F5"||jComboBox1.getSelectedItem()=="F6"
//        ||jComboBox1.getSelectedItem()=="F7"||jComboBox1.getSelectedItem()=="F8"||jComboBox1.getSelectedItem()=="Whipcream"){
//
//
//
////          String grp = (String) jComboBox3.getSelectedItem();
//        Connection connect=null;
//
//        PreparedStatement ps;
//        try {
//           try{
//               connect = DriverManager.getConnection("jdbc:mysql://192.168.1.190:3306/canning?zeroDateTimeBehavior=convertToNull", "weru", "steve23741997");
//
//            ps = connect.prepareStatement("SELECT * FROM logintbl WHERE username = ? AND password = ? AND class=?");
//            // ps = connect.prepareStatement("SELECT * FROM logintbl WHERE username = ? AND password = ? AND class='"ADMINISTRATOR"'");
//            ps.setString(1, jTextField_Username.getText());
//            ps.setString(2, String.valueOf(jPasswordField_Password.getPassword()));
//             ps.setString(3, String.valueOf(jComboBox1.getSelectedItem()));
//            ResultSet rs = ps.executeQuery();
//
//            if(rs.next()){
//              NewJFrame mf = new NewJFrame();
//              mf.setVisible(true);
//
//              jMenu5.setVisible(false);
////              jMenuItem9.setVisible(false);
////               jMenuItem4.setVisible(false);
////                 jMenuItem7.setVisible(false);
////                jMenuItem6.setVisible(false);
//              ExportAndImport exp=new ExportAndImport();
//              exp.setVisible(false);
//
////              NewJFrame.main(null);
////              jTextField_Username.setText(null);
//               jPasswordField_Password.setText(null);
//               this.hide();
//
//
//
//           }else{
//                JOptionPane.showMessageDialog(this, "Username or Password incorrect!");
//               jPasswordField_Password.setText(null);
//            }
//
//                }
//           catch(Exception e){
//                  JOptionPane.showMessageDialog(this, "NO NETWORK ACCESS!");
//                  e.printStackTrace();
//           }
//
//           connect.close();
//
//         } catch (SQLException ex) {
//            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
//}else if(jComboBox1.getSelectedItem()=="ADMINISTRATOR"){
// Connection connect=null;
//
//        PreparedStatement ps;
//        try {
//           try{
//               connect = DriverManager.getConnection("jdbc:mysql://192.168.1.190:3306/canning?zeroDateTimeBehavior=convertToNull", "weru", "steve23741997");
//
//            ps = connect.prepareStatement("SELECT * FROM logintbl WHERE username = ? AND password = ? AND class=?");
//            ps.setString(1, jTextField_Username.getText());
//            ps.setString(2, String.valueOf(jPasswordField_Password.getPassword()));
//             ps.setString(3, String.valueOf(jComboBox1.getSelectedItem()));
//            ResultSet rs = ps.executeQuery();
//
//            if(rs.next()){
//              NewJFrame mf = new NewJFrame();
//              mf.setVisible(true);
//              ExportAndImport exp=new ExportAndImport();
//              exp.setVisible(false);
//
////              NewJFrame.main(null);
////              jTextField_Username.setText(null);
//               jPasswordField_Password.setText(null);
//               this.hide();
//
//
//
//           }else{
//                JOptionPane.showMessageDialog(this, "Username or Password incorrect!");
//               jPasswordField_Password.setText(null);
//            }
//
//                }
//           catch(Exception e){
//                  JOptionPane.showMessageDialog(this, "NO NETWORK ACCESS!");
//                  e.printStackTrace();
//           }
//
//           connect.close();
//
//         } catch (SQLException ex) {
//            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        }else{
//                JOptionPane.showMessageDialog(this, "Username or Password incorrect!");
//               jPasswordField_Password.setText(null);
//            }
    

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton_LoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton_LoginFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_LoginFocusGained

    private void jPasswordField_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordKeyPressed
switch (evt.getKeyCode()){
    case KeyEvent.VK_ENTER:
        LoginForme();
        break;
        default:
            ;
        
    }

//        LoginForme();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_PasswordKeyPressed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1KeyPressed
public static String getItems() {
//    LoginForme1();   
    String Cmbi =(String) jComboBox1.getSelectedItem();

        return Cmbi;
    }
 public static void LoginForme1() {
       ResultSet ras;
        String unamee = jTextField_Username.getText();
        String pwad = String.valueOf(jPasswordField_Password.getPassword());
        jComboBox1.removeAllItems();
        try {
            PreparedStatement claese = db_Connection.getInstance().prepareStatement("select * from logintbl where username=? and password=?");
            claese.setString(1, unamee);
            claese.setString(2, pwad);
            ras = claese.executeQuery();
            while (ras.next()) {
//                String pudii = ras.getString("status");

                jTextField2.setText(ras.getString("class"));
//                jTextField3.setText(ras.getString("class"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
}

    /**
     * @param args the command line arguments
     */
    public void LoginForm() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
//		LookAndFeel("Windows");
//		CheckFiles();

                new LoginForm().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Login;
    private static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_Username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private static javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    private static javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
